
#define JSON_TYPE "application/json"
#define BSON_TYPE "application/bson"
#define QSON_TYPE "application/qson"
#define MULTI_TYPE "multipart/form-data"
#define HEADER_MSG "HTTP/1.0 200 OK\r\nContent-Type:text/html\r\nContent-Length:"
#define NO_CONTENT_MSG    HEADER_TYPE,"000\r\n\r\n"
#define PLAIN_MSG  "PLAIN MSG\r\n\r\n"
#define HTML_MSG  "<html>HTML MSG</html>\r\n"
#define PORT_MSG    "HTTP/1.0 989 No Ports\r\n\r\n"
#define BAD_MSG "HTTP/1.0 200 Not Found\r\n\r\n"
